=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipe.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://cazzscookingcommjunity.github.io/recipe.xsd"
xmlns="https://cazzscookingcommjunity.github.io/recipe.xsd"
elementFormDefault="qualified">

<xs:complexType name="dietType">
    <xs:sequence>
        <xs:element name="LowSugar"/>
        <xs:element name="GlutenFree"/>
        <xs:element name="EggFree"/>
        <xs:element name="NA"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="unitType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="cup"/>
        <xs:enumeration value="tablespoon"/>
        <xs:enumeration value="teaspoon"/>
        <xs:enumeration value="gram"/>
        <xs:enumeration value="ounces"/>
        <xs:enumeration value="kg"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="ingredientType">
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="amount" type="xs:float"/>
    <xs:attribute name="unit" type="unitType"/>
</xs:complexType>


<xs:complexType name="recipeType">
    <xs:all>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="cookTime" type="xs:string"/>
        <xs:element name="recipeCategory" type="xs:string"/>
        <xs:element name="ingredient" type="ingredientType"/>
        <xs:element name="step" type="xs:string"/>
        <xs:element name="yield" type="xs:integer"/>
        <xs:element name="diet" type="dietType"/>
        <xs:element name="prepTime" type="xs:time"/>
        <xs:element name="comment" type="xs:string"/>
        <xs:element name="thumbnailUrl" type="xs:anyURI"/>
        <xs:element name="image" type="xs:anyURI"/>
    </xs:all>
</xs:complexType>

<xs:element name="recipe" type="recipeType"/>

</xs:schema>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/keto_toastie.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io recipe.xsd"> 
                                                                                
    <title>KETO toastie </title>
    <filename>keto_toastie.xml</filename>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    


    <diet>GlutenFree</diet>
    <diet>Keto</diet>

    <ingredient>1 TBsp coconut flour </ingredient>
    <ingredient>1 TBsp grated Parmesan </ingredient>
    <ingredient>1 TBsp grated tasty cheese</ingredient>
    <ingredient>1 TBsp olive oil</ingredient>
    <ingredient>1 egg </ingredient>
    <ingredient>1/4 baking powder </ingredient>
    <ingredient>1 TBsp chopped chives (optional)</ingredient>
    <ingredient>salt and pepper to taste</ingredient>

    <step>
Heat fry pan and add olive oil. While heating beat all ingredients except the tasty cheese, until well combined. Pour two even amounts in pan. Once middle begins to raise you can flip them over. Top one with tasty cheese. Once under side brown stack the plain one on top of the one with cheese. Remove from pan and eat while hot! ðŸ˜‹
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/easy_stir_fry.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd"> 
                                                                                
    <title>Easy Stir Fry</title>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    



    <ingredient>2 chicken breast diced</ingredient>
    <ingredient>2-3 garlic cloves crushed </ingredient>
    <ingredient>3 TBsp oil</ingredient>
    <ingredient>1 stock cube</ingredient>
    <ingredient>1/3 cup stir fry sauce </ingredient>
    <ingredient>1 bag frozen stir fry vegetables </ingredient>
    <ingredient>1 packet pad Thai noodles</ingredient>

    <step>
Cook noodles per packet directions and set aside. Heat oil in wok or large pan. Cook garlic until fragrant then add chicken and cook in batches and remove from pan.  Cook vegetables in pan then add chicken back to pan, along with noodles and sauce. Add salt and pepper if desired and garnish with a couple of chopped spring onions. Serve immediately and place any remaining in fridge, for up till three days.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/sarah_os_brownies.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd"> 
                                                                                
    <title>Sarah Os Brownies</title>
    <filename>sarah_os_brownies.xml</filename>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    



    <ingredient>200gms milk chocolate (broken into small pieces)</ingredient>
    <ingredient>170 gms butter</ingredient>
    <ingredient>1 1/4 cups brown sugar</ingredient>
    <ingredient>3 eggs beaten</ingredient>
    <ingredient>1/2 cup + 1 TBsp flour sifted </ingredient>
    <ingredient>1/3 cup cocoa powder sifted</ingredient>
    <ingredient>3/4 cup white chic chips</ingredient>
    <ingredient>1 cup frozen raspberries (if desired.)</ingredient>

    <step>
Preheat oven to 180D. Grease baking tray and line with baking paper then set aside. Melt butter first then add chocolate and stir until melted. Add sugar and stir until dissolved. Leave to cool for 5 minutes. Add half eggs and half the combined cocoa and flour, then stir well. Add remaining egg and flour mix and stir until completely combined. Stir through chocolate chips and raspberries if using, then pour into prepared tray. Sprinkle top with extra chic chips if desired. Cook for 40 minutes and turn half way through. Once cool cut into slices.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/apple_pie.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd"> 
                                                                                
    <title>Apple Pie</title>

    <comment>If you hate rolling pastry, but love home made style, this is a good one for you!</comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    



    <ingredient>150 gms butter</ingredient>
    <ingredient>2/3 cup sugar</ingredient>
    <ingredient>1 large egg</ingredient>
    <ingredient>2 1/2 cups flour s</ingredient>
    <ingredient>1/3-1/2 cup milk</ingredient>
    <ingredient>Pinch of salt</ingredient>
    <ingredient>Tin of ready apple pie filling (if you want to cheat)</ingredient>

    <step>
Cream sugar and butter, then add egg. Add flour and salt, then milk 1/3 cup first then if it seems dry add the rest to make up to 1/2 cup. Divide in two and roll into balls and wrap in glad wrap and refrigerate for at least an hour. Prepare dish by greasing with a little butter and use your hands to push one ball into the dish to make the base. Pour in apple and make flat with the back of a spoon. Grate the other ball until all used up and top completely covered. Cook in slow oven for one hour. Serve with ice cream and/or cream. Great hot or cold!
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/martys_tiramisu.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Martys Tiramisu</title>
  <filename>martys_tiramisu.xml</filename>
  <comment>this recipe can be doubled or even tripled</comment>
  <thumbnail>martys_tiramisu.jpeg</thumbnail>
  <category>Sweets</category>
  <ingredient>4 eggs separated</ingredient>
  <ingredient>1/2 cup caster sugar</ingredient>
  <ingredient>1-2 cups strong black coffee</ingredient>
  <ingredient>250 gms mascarpone </ingredient>
  <ingredient>1/2 block dark chocolate shaved</ingredient>
  <ingredient>Cocoa (lumps removed)</ingredient>
  <ingredient>1 packet sponge fingers</ingredient>
  <step>Whip eggs whites until soft peaks form.</step>
  <step>Stir egg yolks and sugar together until sugar is dissolved.</step>
  <step>Add the mascarpone to egg yoke mixture.</step>
  <step>Then fold the egg whites into egg yoke mixture, until combined.</step>
  <step>Rub a small amount of this mixture around a square or rectangular pan.</step>
  <step>Place the coffee in a flat dish.</step>
  <step>Dip a sponge finger in the coffee and wet both sides.</step>
  <step>Place a layer of coffee dipped sponge fingers in deep baking dish, then top with a thin layer of egg mixture, covering the surface.</step>
  <step>Sprinkle over a thin layer of cocoa, then sprinkle a thin layer of shaved chocolate.</step>
  <step>Top with another layer of coffee dipped sponge fingers and egg mixture and cocoa and chocolate.</step>
  <step>Repeat layers at least thee times until you reach the top of the pan, finishing with cocoa and chocolate on top layer.</step>
  <step>Cover with glad wrap and place in fridge over night.</step>
  <step>Cut into squares and serve cold.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/vegan_snickers_slice.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd"> 
                                                                                
    <title>Vegan Snickers Slice</title>
    <filename>vegan_snickers_slice.xml</filename>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>


    <diet>GlutenFree</diet>
    <diet>Vegan</diet>

    <part>
        <title>Base</title>
        <ingredient>1/2 cup gluten free oats</ingredient>
        <ingredient>1/2 cup cashews</ingredient>
        <ingredient>1/2 cup almonds or peanuts</ingredient>
        <ingredient>1/2 cup desiccated coconut </ingredient>
        <ingredient>1/4 cup maple syrup</ingredient>
        <ingredient>2 TBsp peanut butter (Mayvers brand or all natural type)</ingredient>
        <ingredient>Pinch of rock salt crushed </ingredient>
        <step>Prepare a square 8</step>
    </part>


    <part>
        <title>Middle</title>
        <ingredient>1 cup Medjool dates pitted and soaked for 30 mins</ingredient>
        <ingredient>1/2 TBsp maple syrup</ingredient>
        <ingredient>1/2 teaspoon vanilla essence</ingredient>
        <ingredient>1/2 cup peanuts</ingredient>
        <ingredient>Pinch of rock salt crushed</ingredient>
    </part>

    <part>
        <title>Top</title>
        <ingredient>1/2 cup copha or coconut oil</ingredient>
        <ingredient>6 TBsp cacao or pure cocoa</ingredient>
        <ingredient>2 TBsp maple syrup</ingredient>
        <ingredient>1/2 cup shredded coconut (if desired)</ingredient>
    </part>

</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/lemon_shortbread.xml
<?xml version='1.0' encoding='UTF-8'?>
<recipe xmlns="https://cazzscookingcommunity.github.io" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Lemon Shortbread </title>
  <filename>lemon_shortbread.xml</filename>
  <comment>c/o irenamacri.com with cazzie tweaks </comment>
  <thumbnail>../images/lemon_shrotbread.jpeg</thumbnail>
  <category>Sweets</category>
  <diet>LowCarb</diet>
  <diet>GlutenFree</diet>
  <ingredient>1 cup Gluten Free flour</ingredient>
  <ingredient>1/3 cup coconut flour </ingredient>
  <ingredient>1/2 cup coconut sugar</ingredient>
  <ingredient>1/2 teaspoon baking powder </ingredient>
  <ingredient>1 egg</ingredient>
  <ingredient>150 gms butter melted </ingredient>
  <ingredient>Zest of one lemon</ingredient>
  <ingredient>2 teaspoon vanilla essence </ingredient>
  <step>Preheat oven to 160C.</step>
  <step>Prepare two trays and line with baking sheet and set aside.</step>
  <step>In a bowl place gluten free flour, coconut flour, coconut sugar, baking powder and lemon zest.</step>
  <step>Stir well with a whisk, then pour in melted butter and stir with a wooden spoon.</step>
  <step>In a separate bowl whisk egg and vanilla essence.</step>
  <step>Pour into mixture and stir with wooden spoon until completely mixed.</step>
  <step>Scoop out heap tablespoon amounts and roll into balls and place evenly spreading them apart covering the trays.</step>
  <step>Push down balls of dough slightly with the back of a fork.</step>
  <step>Place in oven for 10 - 15 minutes or until golden brown.</step>
  <step>Cool completely and store in airtight container.</step>
  <step>Great with a cuppa!.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/rice_bubble_slice.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Rice Bubble Slice</title>
  <filename>rice_bubble_slice.xml</filename>
  <thumbnail>rice_bubble_slice.jpeg</thumbnail>
  <category>Sweets</category>
  <comment>c/o mykidslickthebowl with cazzie tweaks</comment>
  <ingredient>30gms butter</ingredient>
  <ingredient>3 TBsp honey</ingredient>
  <ingredient>1/2 cup Mayvers peanut butter</ingredient>
  <ingredient>3 cups rice bubbles (gluten free if desired or regular)</ingredient>
  <step>Grease a small loaf/slice tray and line with baking paper, then set aside.</step>
  <step>In a saucepan melt the butter, then add the honey and stir until combined.</step>
  <step>Remove from heat and stir in peanut butter.</step>
  <step>Pour in rice bubbles and stir until all the rice bubbles are coated.</step>
  <step>Pour into prepared tray and push down with the back of a spoon.</step>
  <step>(You can sprinkle top with sprinkles if desired at this stage) place in fridge for 3 hours.</step>
  <step>Once set cut into small squares.</step>
  <step>Once slice is set, before cutting you can pour over melted 200gm block of chocolate.</step>
  <step>Replace in fridge until top is set then cut into squares.</step>
</recipe>
