=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipe.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://cazzscookingcommjunity.github.io/recipe.xsd"
xmlns="https://cazzscookingcommjunity.github.io/recipe.xsd"
elementFormDefault="qualified">

<xs:complexType name="dietType">
    <xs:sequence>
        <xs:element name="LowSugar"/>
        <xs:element name="GlutenFree"/>
        <xs:element name="EggFree"/>
        <xs:element name="NA"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="unitType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="cup"/>
        <xs:enumeration value="tablespoon"/>
        <xs:enumeration value="teaspoon"/>
        <xs:enumeration value="gram"/>
        <xs:enumeration value="ounces"/>
        <xs:enumeration value="kg"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="ingredientType">
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="amount" type="xs:float"/>
    <xs:attribute name="unit" type="unitType"/>
</xs:complexType>


<xs:complexType name="recipeType">
    <xs:all>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="cookTime" type="xs:string"/>
        <xs:element name="recipeCategory" type="xs:string"/>
        <xs:element name="ingredient" type="ingredientType"/>
        <xs:element name="step" type="xs:string"/>
        <xs:element name="yield" type="xs:integer"/>
        <xs:element name="diet" type="dietType"/>
        <xs:element name="prepTime" type="xs:time"/>
        <xs:element name="comment" type="xs:string"/>
        <xs:element name="thumbnailUrl" type="xs:anyURI"/>
        <xs:element name="image" type="xs:anyURI"/>
    </xs:all>
</xs:complexType>

<xs:element name="recipe" type="recipeType"/>

</xs:schema>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/jasmines_ice_coffee.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Jasmines Ice Coffee</title>
  <filename>jasmines_ice_coffee.xml</filename>
  <comment/>
  <thumbnail>ice_coffee.jpeg</thumbnail>
  <image/>
  <category/>
  <yield/>
  <prepTime>PT0M</prepTime>
  <cookTime>PT0M</cookTime>
  <ingredient>1/4 cup brewed coffee</ingredient>
  <ingredient>( alternative dissolve 1 teasp instant coffee with 1/4 cup boiling water, then cool)</ingredient>
  <ingredient>1 teasp sugar dissolved in coffee</ingredient>
  <ingredient>Milk </ingredient>
  <ingredient>1 scoop vanilla ice cream </ingredient>
  <ingredient>2-4 ice cubes</ingredient>
  <ingredient>1 teaspoon fresh whipped cream or double cream</ingredient>
  <ingredient>Cocoa</ingredient>
  <step>
In a tall glass pour in coffee. Carefully put in ice cubes, then ice cream into the glass. Pour in enough milk to almost reach the top. Gently scoop the cream on top and sprinkle decoratively with a pinch of cocoa (cocoa can be replaced with chocolate powder), serve with a long spoon!
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/peanut_butter_slice.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Peanut Butter Slice</title>
  <filename>peanut_butter_slice.xml</filename>
  <comment/>
  <thumbnail>peanut_butter_slice.jpeg</thumbnail>
  <image/>
  <category/>
  <yield/>
  <prepTime>PT0M</prepTime>
  <cookTime>PT0M</cookTime>
  <diet>GlutenFree</diet>
  <diet>Vegan</diet>
  <ingredient>1 can chickpeas rinsed and drain </ingredient>
  <ingredient>1/2 cup peanut butter</ingredient>
  <ingredient>1/2 cup maple syrup</ingredient>
  <ingredient>2 teaspoon vanilla </ingredient>
  <ingredient>1/4 teaspoon baking powder </ingredient>
  <ingredient>1/4 teaspoon baking soda</ingredient>
  <ingredient>3/4 cup dark choc chips (dairy free for vegan)</ingredient>
  <ingredient>Pinch of salt</ingredient>
  <step>Grease a small dish and line with grease proof paper.</step>
  <step>Turn on oven to 160 C.</step>
  <step>In a blender add all ingredients except choc chips.</step>
  <step>Blend until combined, then stir in 1/2 cup of choc chips with a spoon.</step>
  <step>Pour into prepared dish and sprinkle over the remaining choc chips.</step>
  <step>Place in oven for 40 minutes or until cooked.</step>
  <step>Cool in pan for 10 minutes then remove to cooling rack.</step>
  <step>Once cool cut into squares.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/roasted_veg_and_buckwheat_salad.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io recipe.xsd"> 
                                                                                
    <title>Roasted Veg and Buckwheat Salad</title>
    <filename>roasted_veg_and_buckwheat_salad.xml</filename>

    <comment>c/o Woolworth with cazzie tweaks </comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>

    <diet>GlutenFree</diet>
    <diet>Vegan</diet>

    <part>
        <title>Salad</title>
        <ingredient>400 gms sweet potatoes</ingredient>
        <ingredient>400 gms pumpkin</ingredient>
        <ingredient>300 gms beets (optional)</ingredient>
        <ingredient>1 red capsicum</ingredient>
        <ingredient>1 TBsp rosemary fine chopped</ingredient>
        <ingredient>3 cloves garlic crushed</ingredient>
        <ingredient>1/3 cup olive oil</ingredient>
        <ingredient>1 cup buckwheat</ingredient>
        <ingredient>2 cups stock</ingredient>
        <ingredient>4-6 cups spinach and rockets</ingredient>
        <ingredient>Lemon wedges to serve</ingredient>
        <step>Preheat oven to 200C. Chop veggies into 3-5 cm pieces. Combine veggies, Rosemary, garlic and 1/4 cup olive oil and mix well with your hands. Place in oven for 30-40 minutes (or until cooked and browning slightly.) </step>

        <step>Meanwhile heat remaining oil in pan and add buckwheat. Cook for 4 minutes and stir continuously. Add stock and bring to the boil. Reduce to a simmer, put a lid on pan and cook for 15 minutes or until most of the stock is absorbed. </step>

        <step>Meanwhile make dressing </step>

        <step>To prepare sprinkle spinach and rocket over a platter, then sprinkle 1/2 of the buckwheat on top. Place roasted veggies on top, then sprinkle remaining buckwheat over the veggies. Lastly drizzle dressing over and scatter a few lemon wedges on the side. Serve with meat if desired or just alone. Very delicious, the entire family went back for seconds!</step>
    </part>

    <part>
        <title>Dressing</title>
        <ingredient>1/4 cup olive oil</ingredient>
        <ingredient>1/4 cup tahini (Mayver brand)</ingredient>
        <ingredient>2 TBsp lemon juice</ingredient>
        <step>add all ingredients togetherand mix well (season if desired.)</step>
    </part>

</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/grandmas_veggie_soup.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd"> 
                                                                                
    <title>Grandmas Veggie Soup</title>
    <filename>grandmas_veggie_soup.xml</filename>

    <comment>This one of my families favourites.  Good to cook on a day you intent spending at home!</comment>
    <thumbnail>../images/placeholder.jpeg</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    



    <ingredient>2 lamb shanks or other lamb bones</ingredient>
    <ingredient>1 swede chopped</ingredient>
    <ingredient>1 turnip chopped</ingredient>
    <ingredient>1 parsnip chopped</ingredient>
    <ingredient>2 celery sticks chopped</ingredient>
    <ingredient>2 large carrots chopped</ingredient>
    <ingredient>250 gms McKenzies soup mix</ingredient>
    <ingredient>1 bay leaf</ingredient>
    <ingredient>Stock to cover </ingredient>
    <ingredient>Salt and Pepper to taste</ingredient>

    <step>
Place all ingredients in a large pot and cover with stock until it is up to your thumb joint over all ingredients. Bring to the boil, then reduce to a simmer. Remove scum from the top and cook until the meat is falling of the bone (about 4-6 hours.) Remove shanks and shred meat with knife and fork. Place all back into the pot, including the bones. Cook until soup thickens, usually another 1-2 hours. Remove bones and season with Salt and Pepper.  Serve with crusty bread. You can freeze the soup or cook in slow cooker on low for 8-10 hours.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/cookie_in_a_cup.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Cookie in a Cup</title>
  <filename>cookie_in_a_cup.xml</filename>
  <thumbnail>cookie _in_a_cup.jpeg</thumbnail>
  <category>Sweets</category>
  <ingredient>2 ceramic cups </ingredient>
  <ingredient>2 TBsp butter</ingredient>
  <ingredient>1 TBsp brown sugar </ingredient>
  <ingredient>1 TBsp sugar</ingredient>
  <ingredient>1/4 teaspoon vanilla</ingredient>
  <ingredient>1/4 teaspoon baking powder</ingredient>
  <ingredient>1/3 cup flour</ingredient>
  <ingredient>1 egg</ingredient>
  <ingredient>Pinch salt</ingredient>
  <step>
In a small jug melt butter for 30 seconds. Add sugars and vanilla stir. Beat egg and stir in, then add flour, baking soda and salt. Stir until lumps removed, then stir through chocolate chips. Pour equally between the two cups and cook individually for 30-40 seconds. Sprinkle over a few more chocolate chips and sprinkle a little cocoa. Serve immediately.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/traditional_shortbread.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                
    <title>Traditional Shortbread</title>
    <filename>traditional_shortbread.xml</filename>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    



    <ingredient>250 gms butter melted</ingredient>
    <ingredient>2 cups plain flour sifted</ingredient>
    <ingredient>2 TBsp rice flour </ingredient>
    <ingredient>1/3 cup icing or castor sugar sifted</ingredient>

    <step>
Preheat oven to 160C and grease a baking tray with butter, then set aside. Mix all ingredients in a bowl until combined. Make a ball with the ingredients, with your hands and move to baking tray. Squash down with your hands until it is about 5mm thick and smooth any cracks. Prick entire surface with fork and bake in oven until just golden. Remove from oven and slice with a knife into small rectangles while still hot. Serve when cold.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/garlic_chilli_chard.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                
    <title>Garlic Chilli Chard</title>

    <comment>c/o Irena Macri</comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    



    <ingredient>1 bunch Swiss or Rainbow Chard</ingredient>
    <ingredient>2 Tbsp olive oil</ingredient>
    <ingredient>1/2 long red chilli finely chopped </ingredient>
    <ingredient>2 cloves of garlic diced</ingredient>
    <ingredient>salt and pepper</ingredient>
    <ingredient>Juice of 1/2 lemon </ingredient>

    <step>
Heat olive oil in a large fry pan. Add the chilli and garlic and stir for 10-20 seconds.  Add the chard, including the stalks, salt and pepper and the lemon juice. Stir for about 3-4 minutes over medium heat. Serve hot as a side dish - very delicious.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/oat_slice.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Oat Slice</title>
  <filename>oat_slice.xml</filename>
  <htmlFilename>oat_slice.html</htmlFilename>
  <comment>c/o oh she glows with cazzie tweaks </comment>
  <thumbnail>oat _slice.jpeg</thumbnail>
  <category>Sweets</category>
  <diet>Vegan</diet>
  <diet>GlutenFree</diet>
  <ingredient>2.5 cups oats</ingredient>
  <ingredient>3 TBsp chia seeds</ingredient>
  <ingredient>1 TBsp ground flax seed</ingredient>
  <ingredient>1 teaspoon cinnamon </ingredient>
  <ingredient>1 teaspoon baking powder </ingredient>
  <ingredient>1/4 teaspoon salt</ingredient>
  <ingredient>1 1/2 cups milk you choose (I used rice milk)</ingredient>
  <ingredient>1/2 cup maple syrup </ingredient>
  <ingredient>2 TBsp nut butter </ingredient>
  <ingredient>1 banana mushed</ingredient>
  <ingredient>1 teaspoon vanilla essence </ingredient>
  <ingredient>1/2 block dairy/GF choc</ingredient>
  <step>Preheat oven to 180C.</step>
  <step>Grease small baking pan and line with grease proof paper.</step>
  <step>Blend one cup of oats first then add all dry ingredients in one bowl and mix well.</step>
  <step>In another bowl mix wet ingredients, except the chocolate.</step>
  <step>Pour wet ingredients into dry ingredients bowl.</step>
  <step>Mix well and pour in prepared pan (it will look quite wet.</step>
  <step>) Bake for 25-30 minutes or until knife comes out clean when inserted a n the centre.</step>
  <step>Edges should be golden brown.</step>
  <step>Carefully remove from tray and cool in wire rack.</step>
  <step>Once mostly cool chop into squares and drizzle over melted chocolate if desired.</step>
</recipe>
