=== cazzscookingcommunity/cazzscookingcommunity.github.io/xml/recipe.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://cazzscookingcommunity.github.io"
xmlns="https://cazzscookingcommunity.github.io"
elementFormDefault="qualified">

<xs:complexType name="dietType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="lowSugar"/>
        <xs:element name="glutenfFree"/>
        <xs:element name="eggFree"/>
        <xs:element name="vegan"/>
        <xs:element name="vegeterian"/>
        <xs:element name="paleo"/>
        <xs:element name="keto"/>
        <xs:element name="elemination"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="unitType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="cup"/>
        <xs:enumeration value="tablespoon"/>
        <xs:enumeration value="teaspoon"/>
        <xs:enumeration value="gram"/>
        <xs:enumeration value="ounces"/>
        <xs:enumeration value="kg"/>
        <xs:enumeration value="ml"/>
        <xs:enumeration value="drops"/>
        <xs:enumeration value="cm"/>
        <xs:enumeration value="inch"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="categoryType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="household"/>
        <xs:enumeration value="breakfast"/>
        <xs:enumeration value="lunch"/>
        <xs:enumeration value="dinner"/>
        <xs:enumeration value="personal"/>
        <xs:enumeration value="soup"/>
        <xs:enumeration value="beef"/>
        <xs:enumeration value="lamb"/>
        <xs:enumeration value="pork"/>
        <xs:enumeration value="poultry"/>
        <xs:enumeration value="fish"/>
        <xs:enumeration value="drink"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="ingredientType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="amount" type="xs:float"/>
        <xs:attribute name="unit" type="unitType"/>
</xs:complexType>

<xs:complexType name="partType">
    <xs:sequence>
    <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
    <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="ingredient" type="ingredientType" minOccurs="1" maxOccurs="unbounded"/>
    <xs:element name="step" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="recipeType">
    <xs:sequence>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="comment" type="xs:string"/>
    <xs:element name="thumbnail" type="xs:anyURI" minOccurs="0"/>
    <xs:element name="image" type="xs:anyURI" minOccurs="0"/>
    <xs:element name="diet" type="dietType" minOccurs="0"/>
    <xs:element name="category" type="categoryType"/>
    <xs:element name="yield" type="xs:integer"/>
    <xs:element name="prepTime" type="xs:int"/>
    <xs:element name="cookTime" type="xs:int"/>
    <xs:element name="part" type="partType" minOccurs="1" maxOccurs="unbounded"/>
    <xs:element name="ingredient" type="ingredientType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="step" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="recipe" type="recipeType"/>

</xs:schema>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/fmn_popcorn_.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
FMN POPCORN 

1/3 cup popcorn
1 TBsp butter (can use coconut oil for vegans)
1 TBsp canola oil 
1 TBsp brown sugar
Cinnamon sugar to taste
Microwave proof bowl with lid

Place butter and oil in microwave proof bowl and melt butter and oil in microwave until butter melted (about 20 seconds.) Mix in brown sugar while still hot and stir all until combined, then add pop corn. Stir to coat all the corn and spread out evenly in the base of the bowl so corn is only one corn kernel deep. Place lid on bowl and cook until most of corn popped. This will depend on your microwave and you may need to experiment to get the timing right. My microwave takes about 3 3/4 minutes (not all the corn will pop!) Remove from microwave with oven mitts and carefully turn inside down and give a good shake. If your lid does not allow you to do this then stir well and ensure to get the melted juices up from the bottom to help coat all the popcorn. Give a good generous shake of cinnamon sugar on top or just plain cinnamon if you don't have cinnamon sugar. Then put your feet up turn on the movie and enjoy!

Check out more popcorn recipes on The Yummy Life web site.
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/middle_eastern_lentil_salad.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                
    <title>Middle Eastern Lentil Salad</title>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>


    <diet>Easy, healthy, quick and yum!</diet>
    <ingredient>FODMAP friendly</ingredient>

    <step>
Can of lentils drained and rinsed 
1/4 cup extra virgin olive oil
1 teaspoon red wine vinegar
1 teaspoon cumin
2 carrots grated 
4 fresh dates pitted and finely chopped
4 spring onions chopped 
8 cups baby spinach
1/4 cup feta in olive oil crumbled
1 cup cherry tomatoes chopped in half
SandP to taste 

Place olive oil , cumin, red wine vinegar and dates in sauce pan and heat on low until warm. Add lentils and reheat then add carrots and season with SandP. Place baby spinach and tomatoes on 4 plates then heap lentil mix on top. Sprinkle spring onions and feta on top. Serve alone or with your choice of meat. I used a pork cutlets for each person seasoned with salt and pepper.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/gluten_free_taco_mix.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
Gluten Free Taco Mix

2 teaspoon cumin
1 teaspoon paprika
1/2 - 1 teaspoon chilli
1 1/2 teaspoon garlic salt
1 teaspoon oregano
 1 teaspoon corn flour
1/4 teaspoon salt

<step>
    Mix all together and use for 500gms-750gms mince meat or 3 cans of beans (mixed, cannelloni and black beans.)
    Serve in tacos with your choice of extras ( cheese, avocado, lettuce, tomatoe ect.
</step>

)
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/smoked_salmon_salad.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                
    <title>smoked-salmon-salad</title>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>



    <ingredient>Smoked Salmon and Cucumber</ingredient>
    <ingredient>(Gluten Free)</ingredient>

    <step>
Ingredients
1/4 cup finely chopped green onions
2 tablespoons plain Greek yogurt
2 tablespoons mayonnaise
2 tablespoons drained capers
1 tablespoon chopped fresh dill, divided
1 (12-ounce) package cold-smoked salmon, coarsely chopped
3 English cucumbers
1/8 teaspoon freshly ground black pepper
Preparation

1. Combine first 4 ingredients in a medium bowl. Stir in 2 teaspoons dill and chopped salmon.

2. Peel cucumbers in alternating vertical stripes. Cut cucumbers into 3/4-inch-thick slices, and scoop out seeds with a small spoon or melon baller, leaving bottom intact to form a cup.

3. Spoon about 1 tablespoon salmon mixture into each cucumber cup. Sprinkle cups evenly with remaining 1 teaspoon dill and pepper.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/pea_and_ham_soup.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
Pea and Ham Soup
FODMAP friendly

Packet green split peas
2 large carrots chopped
1 teaspoon mixed spice
1 teaspoon pepper
1-2 bay leaves
1-2 garlic cloves crushed
1 whole ham hock (Bertocchi)
SandP to taste

Rinse peas under running water and remove any foreign objects. Place in large pot with all other ingredients except SandP.  Pour in enough water to cover everything plus up to your thumb joint more. Bring to the boil then turn down to a simmer until meat is falling off the bone (4-6hrs.) Remove hock from soup and remove skin and discard. Shred the meat with a small knife or two forks. Place back in soup with the bones, these will help thicken the soup. When the soup is at your desired thickness remove the bones and add SandP to taste, check first before adding. Some hocks are more salty than others. Bertocchi ham hocks give the most consistent best flavour. This recipe takes hours and is one for a rainy day spent inside, but well worth it!
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/awesome_roast_spuds.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io recipe.xsd"> 
                                                                                
    <title>Awesome Roast Spuds</title>
    <filename>awesome_roast_spuds.xml</filename>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    



    <ingredient>10 white potatoes </ingredient>
    <ingredient>1/2 cup duck fat melted </ingredient>
    <ingredient>Salt</ingredient>

    <step>
Preheat oven to 180C. Peel spuds and cut in half. Place in a microwave proof bowl and fill with water until spuds covered and sprinkle with 1/2 teaspoon salt. Microwave for 20-30 minutes. The spuds should be mostly done and not falling apart. Drain well in a colander and shake gently to knock the sides up a bit. Pour into a baking dish and pour in the melted duck fat. Mix together until spuds are all coated. Place in oven for 60 minutes or until golden brown. You can turn them over, halfway through the cooking. Salt generously and serve with roast meat if desired. (When cooking with roast meat I get the meat in the oven then start preparing my spuds next.)
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/cottage_pie.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
Cottage Pie
FODMAP friendly

One amount of mashed spud
600 gms mince meat (lamb)
2-4 garlic cloves crushed
2 carrots grated
1/2 cup frozen peas defrosted or a zucchini grated
2 Tbsps tomatoe sauce
2 Tbsps Worcestershire sauce
1 Tbsp corn flour 
1-2 stock cubes 
Olive oil 
SandP to taste

Preheat oven to 180 degrees. Heat olive oil in large fry pan and add garlic. Once golden add mince meat and cook until brown add all other ingredients except spud. Cook until reheated and sauce thickens. Place in a tray and spoon over mash spud. Cook for 30-40 minutes or until golden brown. Serve with side salad or lots of tomatoe sauce!
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/large_banana_bread.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                
    <title>Large Banana Bread</title>

    <comment></comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>


    <diet>Super Easy</diet>
    <ingredient>(Good for a crowd or taking somewhere)</ingredient>

    <step>
2 cups flour
1 cup sugar
1/4 teaspoon baking powder
1 teaspoon cinnamon 
2 teaspoon baking soda
1/2 teaspoon salt
1 cup chopped walnuts ( nuts optional)
1 cup oil
1 teaspoon vanilla
3 eggs beaten
2 cups mashed bananas (2-3 bananas)

Turn on oven to 170D. Grease 20cm x 12cm dish or two loaf trays and set aside.  Combine all ingredients, except bananas and mix well. Add bananas and fold through, then pour into prepared tray. Smooth over top and place in oven for 40-60 minutes or until skew come out clean. Remove from oven and cover immediately with foil. Wait 10-15 minutes before serving while warm or wait until completely cold. You can sprinkle with a little icing sugar when serving.

NB-When my bananas go spotty I pop them in the the freezer. When I have three bananas I make a cake. They look pretty horrible when defrosted, but it makes the cake taste awesome!
*Pam Wolfs recipe
    </step>
</recipe>
