=== cazzscookingcommunity/cazzscookingcommunity.github.io/xml/recipe.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://cazzscookingcommunity.github.io"
xmlns="https://cazzscookingcommunity.github.io"
elementFormDefault="qualified">

<xs:complexType name="dietType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="lowSugar"/>
        <xs:element name="glutenfFree"/>
        <xs:element name="eggFree"/>
        <xs:element name="vegan"/>
        <xs:element name="vegeterian"/>
        <xs:element name="paleo"/>
        <xs:element name="keto"/>
        <xs:element name="elemination"/>
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="unitType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="cup"/>
        <xs:enumeration value="tablespoon"/>
        <xs:enumeration value="teaspoon"/>
        <xs:enumeration value="gram"/>
        <xs:enumeration value="ounces"/>
        <xs:enumeration value="kg"/>
        <xs:enumeration value="ml"/>
        <xs:enumeration value="drops"/>
        <xs:enumeration value="cm"/>
        <xs:enumeration value="inch"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="categoryType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="household"/>
        <xs:enumeration value="breakfast"/>
        <xs:enumeration value="lunch"/>
        <xs:enumeration value="dinner"/>
        <xs:enumeration value="personal"/>
        <xs:enumeration value="soup"/>
        <xs:enumeration value="beef"/>
        <xs:enumeration value="lamb"/>
        <xs:enumeration value="pork"/>
        <xs:enumeration value="poultry"/>
        <xs:enumeration value="fish"/>
        <xs:enumeration value="drink"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="ingredientType">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="amount" type="xs:float"/>
        <xs:attribute name="unit" type="unitType"/>
</xs:complexType>

<xs:complexType name="partType">
    <xs:sequence>
    <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"/>
    <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="1"/>
    <xs:element name="ingredient" type="ingredientType" minOccurs="1" maxOccurs="unbounded"/>
    <xs:element name="step" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="recipeType">
    <xs:sequence>
    <xs:element name="title" type="xs:string"/>
    <xs:element name="comment" type="xs:string"/>
    <xs:element name="thumbnail" type="xs:anyURI" minOccurs="0"/>
    <xs:element name="image" type="xs:anyURI" minOccurs="0"/>
    <xs:element name="diet" type="dietType" minOccurs="0"/>
    <xs:element name="category" type="categoryType"/>
    <xs:element name="yield" type="xs:integer"/>
    <xs:element name="prepTime" type="xs:int"/>
    <xs:element name="cookTime" type="xs:int"/>
    <xs:element name="part" type="partType" minOccurs="1" maxOccurs="unbounded"/>
    <xs:element name="ingredient" type="ingredientType" minOccurs="0" maxOccurs="unbounded"/>
    <xs:element name="step" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="recipe" type="recipeType"/>

</xs:schema>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/natural_homemade_face_scrub.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io recipe.xsd"> 
                                                                                
    <title>Natural Homemade Face Scrub</title>
    <filename>natural_homemade_face_scrub.xml</filename>

    <comment>c/o iamvanessae (You Tube)</comment>
    <thumbnail>../images/placeholder.png</thumbnail>
    <image></image>
    <category>Personal</category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>

    <part>
        <title>Coffee Scrub</title>
        <ingredient>1/4 cup fresh coffee grounds </ingredient>
        <ingredient>2 TBSP coconut oil</ingredient>
        <step></step>
    </part>

    <part>
        <title>Olive Oil Scrub</title>
        <ingredient>3 TBSP olive oil</ingredient>
        <ingredient>1/4 cup sugar</ingredient>
        <step>
            Mix ingredients until combine and decant into repurposed jars. Use once or twice a week. (I use mine while Im in the shower!)
            Coffee Scrub can be used on your body also.
        </step>
    </part>


</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/chowder.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
CHOWDER
Gluten Free

1 can creamed corn 
4 potatoes peeled and chopped
2 large carrots chopped
200-300gms diced bacon
2 chicken stock cubes
Milk and Water
Oil
SandP to taste

Heat oil in large pot and cook the bacon until brown.  Add can of creamed corn then fill can with milk and pour into pot then do the same with water. Add all other ingredients and bring to simmer. Cook until veggies are soft, stir every now and then, to stop bottom catching (about 30-45 mins) Serve with thick toast or fresh bread if desired. You can double recipe.  Great for a cold winter lunch!
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/xml/cazzies_smoothy.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io ../../xml/recipe.xsd">
  <title>Cazzies Smoothy</title>
  <filename>cazzies_smoothy.xml</filename>
  <thumbnail>cazzie_smoothy.jpeg</thumbnail>
  <category>Drink</category>
  <ingredient>1 old banana</ingredient>
  <ingredient>1/2 cup frozen strawberries </ingredient>
  <ingredient>1/4 frozen raspberries </ingredient>
  <ingredient>1/2 cup vanilla yogurt</ingredient>
  <ingredient>1 cup milk (can substitute with rice, soy, almond ect)</ingredient>
  <step>Place all ingredients in blender and blend until smooth! Serve in tall glass.</step>
  <step>Can be doubled.</step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/potatoe_and_leek_soup.xml
<?xml version='1.0' encoding='UTF-8'?>
<recipe xmlns="https://cazzscookingcommunity.github.io" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cazzscookingcommunity.github.io https://cazzscookingcommunity.github.io/xml/recipe.xsd">
  <title>Potatoe and Leek Soup</title>
  <filename>potatoe_and_leek_soup.xml</filename>
  <thumbnail>../images/potatoe_and_leek_loup.jpeg</thumbnail>
  <category>Soup</category>
  <diet>GlutenFree</diet>
  <diet>Vegan</diet>
  <ingredient>2 leeks white part chopped</ingredient>
  <ingredient>8-10 Potatoes chopped</ingredient>
  <ingredient>3-4 garlic cloves crushed</ingredient>
  <ingredient>2-4 TBsp olive oil</ingredient>
  <ingredient>10 cups stock</ingredient>
  <ingredient>S and white P to taste</ingredient>
  <step>
In a large pot heat oil and slow cook garlic for 5-7 minutes. Add remaining ingredients, except salt and pepper, and bring to the boil. Reduce and simmer until spuds can be crushed easily on the side of the pot (about 30-40 mins.) turn of heat and blend with stick blender, until all combined and smooth. Add salt and pepper to taste. (Re-heat if necessary.) Serve with crusty bread if desired.
    </step>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/easiest_scones_in_the_world.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
Easiest Scones in the WORLD

Plain
4 cups SR flour
300 mls cream
300 mls water
Pinch salt

Date scones
*for date scones include:
250 gms dates chopped
3 TBsp sugar

Turn on oven to medium (180D). Grease a large flat tray and set aside. In a large bowl stir the dry ingredients. Pour in the cream and water and stir with a KNIFE until combined. Do not over stir! Tip out to a generously floured surface and turn once to flour all sides. Gently push down to desired thickness about thumb joint high. Cut out with scone cutter or small glass and place close together on tray. ( Unlike cookies you want them touching.) Cook until just starting to change colour, about 20-40 minutes. Turn the tray around a few time to ensure all sides brown evenly while cooking. Sever with whipped cream and jam and hot cup of tea!
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/recipes/black_bean_salad.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='/xml/xsd2html2xml/xsd2html2xml.xsl'?>
<recipe xmlns="https://cazzscookingcommunity.github.io"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://cazzscookingcommunity.github.io /xml/recipe.xsd">
  <title>Black Bean Salad</title>
  <filename>black_bean_salad.xml</filename>
  <thumbnail>blackbean_salad.jpeg</thumbnail>
  <category/>
  <part>
    <title>Main</title>
    <ingredient>1 can black beans rinsed and drained</ingredient>
    <ingredient>1 can corn drained</ingredient>
    <ingredient>1 red capsicum diced</ingredient>
    <ingredient>3-4 spring onions chopped </ingredient>
    <ingredient>1/2 bunch parsley finely chopped</ingredient>
    <step>Put all Salad ingredients in a medium bowl and stir well to mix. Place dressing ingredients in a small jar and shake well. Pour dressing over salad just before serving and mix well.</step>
  </part>
  <part>
    <title>Dressing</title>
    <ingredient>3 TBsp olive oil</ingredient>
    <ingredient>1 TBsp balsamic vinegar</ingredient>
    <ingredient>1/2 teaspoon Dijon mustard</ingredient>
    <ingredient>salt and pepper to taste</ingredient>
    <step>mix in jar and shake</step>
  </part>
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/mm_pasties.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
MM Pasties
(Great for a crowd- or grand final party)

10 sheets puff pastry
5-6 spuds grated
2 big carrots grated
1 turnip grated
1 pasnip grated
2 celery sticks finely chopped
1 onion grated
800-1000 gms mince meat
1 TBsp each salt and pepper
Milk for glazing

Grease baking trays and set aside. Heat oven to 180D. Mix all ingredients in large pot with your hands. Lay out one sheet of defrosted puff pastry on work surface and place mixed ingredient 2 1/2 handfuls off centre, then fold over pastry so edges are touching. Cut off excess triangle of pastry. Fold over edges and press firmly down with fingers. Place on baking tray and paint with some milk. Continue until you Use up all mixed ingredients. Cook at 180D (you may have to adjust to your stove) for 1 hour or until golden brown. Turn several times while cooking.
</recipe>

=== cazzscookingcommunity/cazzscookingcommunity.github.io/fb_recipes/elimination_diet_part1.xml
<?xml version="1.0" encoding="UTF-8"?>

<recipe 
xmlns="https://cazzscookingcommunity.github.io" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="https://cazzscookingcommunity.github.io ../xml/recipe.xsd"> 
                                                                                

    <title></title>
    <comment></comment>
    <thumbnail></thumbnail>
    <image></image>
    <diet></diet>
    <category></category>
    <yield></yield>
    <prepTime></prepTime>
    <cookTime></cookTime>
    <part></part>
    <ingredient name="" amount="" unit=""></ingredient>
    <step></step>
ELIMINATION DIET_part1
Part 1
If you need to work out what you are allergic to or just want to detox!
This is a suggested plan from a Sydney Hospital.
Instructions in the next post.
</recipe>
